[project]
name = "razorpay-mcp-server"
version = "1.0.0"
description = "Model Context Protocol (MCP) server for Razorpay payment integration"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "jsonschema>=4.23.0",
    "mcp>=1.6.0",
    "razorpay>=1.4.2",
]
